### ISSUE TITLE
Display device changing progress

### ISSUE THREAD

**Issue by azuzunaga** [Kif11/anticap#3]
Display which device number out of total is being tested for each mac-address-change-ping-google iteration: `Testing device 3 out of 93`.

**Comment by Kif11** [comment]
Good suggestion will do!

**Comment by Kif11** [comment]
This is good. Thanks! Was the tool working for you overall?

**Comment by azuzunaga** [comment]
Awesome! I had intermittent success with it, but I haven't been thorough
enough testing it that I could tell you why.

Americo

**Comment by Kif11** [comment]
This approach is not a silver bullet but it works in 80% of all cases for me.

**Comment by azuzunaga** [comment]
Yes of course. Overall I'm very happy this exists 😃
